### PR TITLE
RTEMS Serial Transport support

### PR DESCRIPTION
**Pull request by roncapat**
Following #283 and #287, made a rapid patch for serial transport support. 
Tested with PingPong app as usual.

Details about how to test this transport using QEMU will be added in https://github.com/micro-ROS/micro_ros_setup/issues/397 tracker issue.

Note: as for TCP/UDP, this patch implements a variant of POSIX transports using `select()` call instead of `poll()` call, which is not officially supported by RTEMS 5 core. Even if RTEMS-libBSD adds some `poll()` support, many boards (BSPs) would be potentially excluded from microROS usage due to inability to build libBSD for them.

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/509/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/525/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/510/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/526/)

**Comment by pablogs9** [comment]
Can you rebase this onto `develop` and make this PR target `develop`?

**Comment by roncapat** [comment]
@pablogs9 done. Poll me if I have messed up something in the process.

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/511/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/527/)

**Review by pablogs9 — APPROVED** [review]
LGTM

@Acuadros95 S&M if you are ok

**Pull request merged**
