### PR TITLE
Implement ping functionality to check agent's availability

### PR DESCRIPTION
**Pull request by jamoralp**
TODO:
- [x] Testing -> https://github.com/eProsima/Micro-XRCE-DDS/issues/57

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/182/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/187/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/184/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/189/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/185/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/190/)

**Review by pablogs9 — APPROVED** [review]

**Comment by pablogs9** [comment]
LGTM, should we create a related issue in the general Micro XRCE-DDS repo to remember to add a test to this feature there?

**Comment by jamoralp** [comment]
> LGTM, should we create a related issue in the general Micro XRCE-DDS repo to remember to add a test to this feature there?

Yes, I just did it here https://github.com/eProsima/Micro-XRCE-DDS/issues/57

**Pull request merged**
