### PR TITLE
Fix Custom MTU

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Review by jamoralp — DISMISSED** [review]

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/227/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/237/)

**Comment by jamoralp** [comment]
sorry for the approval. You should change the value in custom_transport.h and custom_transport.c. Am I right?

**Comment by pablogs9** [comment]
Fixed

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/228/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/238/)

**Review by jamoralp — APPROVED** [review]

**Pull request merged**
