### PR TITLE
common path for all posix targets [6001]

### PR DESCRIPTION
**Pull request by iluetkeb**
Currently, NuttX is not properly considered in the includes.

This was previously hidden by the fact that the NuttX toolchain definition set the CMAKE_SYSTEM_NAME to "Linux" in apps/uros/arm_toolchain.cmake. However, that's a problematic thing to do and should be avoided whenever possible. See https://github.com/microROS/apps/pull/5 for a PR to change it.

Once that's changed, Micro-XRCE-DDS-Client will have a problem, which is then fixed by this PR introducing a "PLATFORM_POSIX" define, to treat all Posix-like OS's with the same code.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro%20XRCE-DDS%20Client%20Manual%20Linux/156/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro%20XRCE-DDS%20Client%20Manual%20Windows/117/)
* NuttX [Build Status](http://jenkins.eprosima.com:8080/job/Micro%20XRCE-DDS%20Client%20Manual%20NuttX/98/)

**Comment by BorjaOuterelo** [comment]
Note that we have our own toolchain file in our develop branch: [nuttx_toolchain](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/develop/toolchains/nuttx_toolchain.cmake) with the system name and platform correctly set.

Regarding the "PLATFORM_POSIX" define could be avoided here, as we not only use those macros to select APIs also to select tested or working/not working functionality. In this concrete case, UDP discovery was not tested in NuttX, so it is only available in Linux, not all POSIX platforms.

With all this, I guess that your PR to micro-ROS will not affect micro XRCE-DDS compilation as it is now if we set PLATFORM_NAME in the micro-ROS toolchain.
Do you think that could work?

Note that also we have some changes in https://github.com/eProsima/Micro-XRCE-DDS-Nuttx-Apps/tree/microxrce_dev/microxrcedds that we may want to integrate into the micro-ROS NuttX apps repository. In this case, the toolchain is provided by micro-XRCE-DDS and used in the compilation of the library.

**Comment by iluetkeb** [comment]
Hi,

note that I'm not suggesting the Linux/NuttX-specific macros, however, for things which are common to all posix systems, we can use a common define.

btw, I've seen your toolchain file, but could not determine where it is used.

Best Regards / Mit freundlichen Grüßen

--
Dr. Ingo Lütkebohle
CR/AEX3

Tel. +49(711)811-12248 | Mobil +49-1525-8813417

► Take a look at Bosch Research: www.bosch.com/research

________________________________________
Von: Borja Outerelo <notifications@github.com>
Gesendet: Donnerstag, 14. März 2019 12:12:10
An: eProsima/Micro-XRCE-DDS-Client
Cc: Luetkebohle Ingo (CR/AEX3); Author
Betreff: Re: [eProsima/Micro-XRCE-DDS-Client] common path for all posix targets (#82)

Note that we have our own toolchain file in our develop branch: nuttx_toolchain<https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/develop/toolchains/nuttx_toolchain.cmake> with the system name and platform correctly set.

Regarding the "PLATFORM_POSIX" define could be avoided here, as we not only use those macros to select APIs also to select tested or working/not working functionality. In this concrete case, UDP discovery was not tested in NuttX, so it is only available in Linux, not all POSIX platforms.

With all this, I guess that your PR to micro-ROS will not affect micro XRCE-DDS compilation as it is now if we set PLATFORM_NAME in the micro-ROS toolchain.
Do you think that could work?

Note that also we have some changes in https://github.com/eProsima/Micro-XRCE-DDS-Nuttx-Apps/tree/microxrce_dev/microxrcedds that we may want to integrate into the micro-ROS NuttX apps repository. In this case, the toolchain is provided by micro-XRCE-DDS and used in the compilation of the library.

**Comment by BorjaOuterelo** [comment]
The toolchain is used in
https://github.com/eProsima/Micro-XRCE-DDS-Nuttx-Apps/blob/microxrce_dev/microxrcedds/Makefile#L128
That Makefile should be integrated in the micro-ROS NuttX Apps.

**Comment by iluetkeb** [comment]
Just came across this old issue, which is still not resolved. I don't think using your microxrcedds Makefile, will solve the issue because it does not address the compilation issue. It surmise that it works for you only because there is nobody actually including the UDP transport header files.

Do you have a use-case where you're compiling a micro-ros (!) app on nuttx?

**Comment by iluetkeb** [comment]
Okay, so I looked at this a bit more and you're turning off PROFILE_DISCOVERY in your Makefile, and since the rest works, it compiles then. I was exactly trying to use discovery, however.

In any case, I've added this configuration setting to the micro_ros_setup build approach for now.

**Comment by julianbermudez** [comment]
Hi @iluetkeb,

I fixed Discovery compilation for NuttX in [feature/nuttx](https://github.com/eProsima/Micro-XRCE-DDS-Client/tree/feature/nuttx). This is a provisional fix because I want to rename the _x_linux_ files to POSIX and use your `PLATFORM_TYPE_POSIX`. I also modified the Makefile in [apps](https://github.com/eProsima/Micro-XRCE-DDS-Nuttx-Apps/tree/microxrce_dev) adding a discovery profile option.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/6/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/4/)

**Comment by julibert** [comment]
Hi @iluetkeb, this issue was addressed at #98.

**Pull request closed without merging**
