### PR TITLE
Followup #283 - RTEMS - select() fixes

### PR DESCRIPTION
**Pull request by roncapat**
As suggested by @Acuadros95 I simplified the code copying the set to a local variable. Also fixed the discovery.

### CODE REVIEW

**Comment by roncapat** [comment]
Fixing DCO after uncrustify test

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/485/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/501/)

**Review by Acuadros95 — APPROVED** [review]

**Comment by Acuadros95** [comment]
LGTM!

**Comment by roncapat** [comment]
Ahh sorry messed up. Will fix

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/486/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/502/)

**Comment by roncapat** [comment]
@Acuadros95 now clean and signed. Sorry for the confusion.

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/487/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/503/)

**Comment by pablogs9** [comment]
@Acuadros95 remember to move the `ros2` and `foxy` branches to the last commit in `develop`

**Pull request merged**
