### PR TITLE
Release v2.4.1

### PR DESCRIPTION
**Pull request by Acuadros95**

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/599/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/618/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/600/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/619/)

**Comment by gavanderhoorn** [comment]
Just curious: why did b8dbfaa775d0d842edfa9a0eb2ebc8ebdb1a0c14 revert the bump to `2.0.2` of Micro-CDR?

**Comment by pablogs9** [comment]
Not sure, I guess that this is a sort of revert on a 96ec27152d2013ed7c13fb578697178f37d75757 mistake (?). 

Not sure, in any case, I will recheck the versioning and will set all the package dependencies to the latest version on the next Micro XRCE-DDS release next month.

**Comment by gavanderhoorn** [comment]
It's unfortunate the commit message doesn't explain why it was reverted.

**Comment by pablogs9** [comment]
I found it, the reason of the revert is that 2.0.2 does not exist https://github.com/eProsima/Micro-CDR/releases

**Pull request merged**
