### PR TITLE
Fix heartbeat period to 100ms

### PR DESCRIPTION
**Pull request by Acuadros95**

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/416/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/430/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/417/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/431/)

**Comment by pablogs9** [comment]
Please comment here the related PR in https://github.com/eProsima/Micro-XRCE-DDS

**Comment by Acuadros95** [comment]
Testing PR: https://github.com/eProsima/Micro-XRCE-DDS/pull/96

Passing on Linux and Windows

**Review by pablogs9 — APPROVED** [review]

**Pull request merged**
