### PR TITLE
Fix fragmentation & typo

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/266/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/276/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/267/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/277/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/270/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/280/)

**Review by jamoralp — DISMISSED** [review]

**Comment by pablogs9** [comment]
@jamoralp This fix is not needed if XRCE reliable history is power of two, as is explained in the docs. 

But what do you think about keeping this check in order to avoid segfaults if the user misconfigures the middleware? We have two options:
- [ ] We can assume some deserializing errors when `seqnum` rollover and the in the case of `history` is not 2^N
- [ ] We will have segfaults when `seqnum` rollover and the history is not 2^N

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Linux/271/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Client%20Manual%20Windows/281/)

**Comment by jamoralp** [comment]
I ticked the option that I consider more appropriate, although the problem is not totally fixed. Having a segfault is not something that should happen, in my opinion.

**Comment by pablogs9** [comment]
So we can merge this if you are ok

**Review by jamoralp — APPROVED** [review]

**Pull request merged**
